version: '3.8'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net

  springboot:
    image: openjdk:17-jdk
    container_name: springboot
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ["java", "-jar", "springboot-0.0.1-SNAPSHOT.jar"]
    ports:
      - "8080:8080"
    networks:
      - app-net

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - springboot
    networks:
      - app-net

networks:
  app-net:
